POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
    "valor": 10000,
    "tipo": "d",
    "descricao":  "Teste"
}

###

GET http://localhost:9999/clientes/1/extrato


###
