POST http://localhost:30001/clientes/1/transacoes
Content-Type: application/json

{
    "valor": 1,
    "tipo": "d",
    "descricao":  "teste"
}

###

GET http://localhost:30001/clientes/1/extrato


###
